### ISSUE TITLE
recyclerview can't add header or footer

### ISSUE THREAD

**Issue by sungerk** [MarkoMilos/Paginate#12]

**Comment by MarkoMilos** [comment]
I'm closing this since it is not properly reported issue. 

Solution to your problem is to create an recyclerview adapter with 3 types of list item 
1. header
2. content type
3. footer

You can add whatever you want with those items (any view can be added).

Unline ListView, RecyclerView doesn't have methods for adding headers and footers - it is not problem of Paginate library
